// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace test2.TicketDetailUIMapClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public partial class TicketDetailUIMap
    {
        
        /// <summary>
        /// ReturnToList
        /// </summary>
        public void ReturnToList()
        {
            #region Variable Declarations
            HtmlHyperlink uIBacktoListHyperlink = this.UIDetailsWindowsInternWindow.UIDetailsDocument.UIContentCustom.UIBacktoListHyperlink;
            #endregion

            // Click 'Back to List' link
            Mouse.Click(uIBacktoListHyperlink, new Point(45, 7));
        }
        
        /// <summary>
        /// AssertTicketTitle - Use 'AssertTicketTitleExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertTicketTitle()
        {
            #region Variable Declarations
            HtmlCustom uIItemCustom = this.UIDetailsWindowsInternWindow.UIDetailsDocument1.UIContentCustom.UIItemCustom;
            #endregion

            // Verify that the 'InnerText' property of custom control equals 'Sample ticket'
            Assert.AreEqual(this.AssertTicketTitleExpectedValues.UIItemCustomInnerText, uIItemCustom.InnerText, "El titulo del ticket no es el esperado");
        }
        
        /// <summary>
        /// AssertDescription - Use 'AssertDescriptionExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertDescription()
        {
            #region Variable Declarations
            HtmlCustom uIItemCustom1 = this.UIDetailsWindowsInternWindow.UIDetailsDocument1.UIContentCustom.UIItemCustom1;
            #endregion

            // Verify that the 'InnerText' property of custom control equals 'This is a sample ticket'
            Assert.AreEqual(this.AssertDescriptionExpectedValues.UIItemCustom1InnerText, uIItemCustom1.InnerText);
        }
        
        #region Properties
        public virtual AssertTicketTitleExpectedValues AssertTicketTitleExpectedValues
        {
            get
            {
                if ((this.mAssertTicketTitleExpectedValues == null))
                {
                    this.mAssertTicketTitleExpectedValues = new AssertTicketTitleExpectedValues();
                }
                return this.mAssertTicketTitleExpectedValues;
            }
        }
        
        public virtual AssertDescriptionExpectedValues AssertDescriptionExpectedValues
        {
            get
            {
                if ((this.mAssertDescriptionExpectedValues == null))
                {
                    this.mAssertDescriptionExpectedValues = new AssertDescriptionExpectedValues();
                }
                return this.mAssertDescriptionExpectedValues;
            }
        }
        
        public UIDetailsWindowsInternWindow UIDetailsWindowsInternWindow
        {
            get
            {
                if ((this.mUIDetailsWindowsInternWindow == null))
                {
                    this.mUIDetailsWindowsInternWindow = new UIDetailsWindowsInternWindow();
                }
                return this.mUIDetailsWindowsInternWindow;
            }
        }
        #endregion
        
        #region Fields
        private AssertTicketTitleExpectedValues mAssertTicketTitleExpectedValues;
        
        private AssertDescriptionExpectedValues mAssertDescriptionExpectedValues;
        
        private UIDetailsWindowsInternWindow mUIDetailsWindowsInternWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertTicketTitle'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class AssertTicketTitleExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of custom control equals 'Sample ticket'
        /// </summary>
        public string UIItemCustomInnerText = "Sample ticket";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertDescription'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class AssertDescriptionExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'InnerText' property of custom control equals 'This is a sample ticket'
        /// </summary>
        public string UIItemCustom1InnerText = "This is a sample ticket";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIDetailsWindowsInternWindow : BrowserWindow
    {
        
        public UIDetailsWindowsInternWindow()
        {
            #region Search Criteria
            this.SearchProperties[UITestControl.PropertyNames.Name] = "Details";
            this.SearchProperties[UITestControl.PropertyNames.ClassName] = "IEFrame";
            this.WindowTitles.Add("Details");
            #endregion
        }
        
        public void LaunchUrl(System.Uri url)
        {
            this.CopyFrom(BrowserWindow.Launch(url));
        }
        
        #region Properties
        public UIDetailsDocument UIDetailsDocument
        {
            get
            {
                if ((this.mUIDetailsDocument == null))
                {
                    this.mUIDetailsDocument = new UIDetailsDocument(this);
                }
                return this.mUIDetailsDocument;
            }
        }
        
        public UIDetailsDocument1 UIDetailsDocument1
        {
            get
            {
                if ((this.mUIDetailsDocument1 == null))
                {
                    this.mUIDetailsDocument1 = new UIDetailsDocument1(this);
                }
                return this.mUIDetailsDocument1;
            }
        }
        #endregion
        
        #region Fields
        private UIDetailsDocument mUIDetailsDocument;
        
        private UIDetailsDocument1 mUIDetailsDocument1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIDetailsDocument : HtmlDocument
    {
        
        public UIDetailsDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Details";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/ServiceTickets/Details/16";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://intranet.fabrikam.com/ServiceTickets/Details/16";
            this.WindowTitles.Add("Details");
            #endregion
        }
        
        #region Properties
        public UIContentCustom UIContentCustom
        {
            get
            {
                if ((this.mUIContentCustom == null))
                {
                    this.mUIContentCustom = new UIContentCustom(this);
                }
                return this.mUIContentCustom;
            }
        }
        #endregion
        
        #region Fields
        private UIContentCustom mUIContentCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIContentCustom : HtmlCustom
    {
        
        public UIContentCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["Id"] = "content";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.SearchProperties["TagName"] = "SECTION";
            this.FilterProperties["Class"] = null;
            this.FilterProperties["ControlDefinition"] = "id=\"content\"";
            this.FilterProperties["TagInstance"] = "1";
            this.WindowTitles.Add("Details");
            #endregion
        }
        
        #region Properties
        public HtmlHyperlink UIBacktoListHyperlink
        {
            get
            {
                if ((this.mUIBacktoListHyperlink == null))
                {
                    this.mUIBacktoListHyperlink = new HtmlHyperlink(this);
                    #region Search Criteria
                    this.mUIBacktoListHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Id] = null;
                    this.mUIBacktoListHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Name] = null;
                    this.mUIBacktoListHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.Target] = null;
                    this.mUIBacktoListHyperlink.SearchProperties[HtmlHyperlink.PropertyNames.InnerText] = "Back to List";
                    this.mUIBacktoListHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.AbsolutePath] = "/ServiceTickets";
                    this.mUIBacktoListHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Title] = null;
                    this.mUIBacktoListHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Href] = "http://intranet.fabrikam.com/ServiceTickets";
                    this.mUIBacktoListHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.Class] = null;
                    this.mUIBacktoListHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.ControlDefinition] = "href=\"/ServiceTickets\"";
                    this.mUIBacktoListHyperlink.FilterProperties[HtmlHyperlink.PropertyNames.TagInstance] = "8";
                    this.mUIBacktoListHyperlink.WindowTitles.Add("Details");
                    #endregion
                }
                return this.mUIBacktoListHyperlink;
            }
        }
        #endregion
        
        #region Fields
        private HtmlHyperlink mUIBacktoListHyperlink;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIDetailsDocument1 : HtmlDocument
    {
        
        public UIDetailsDocument1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.Id] = null;
            this.SearchProperties[HtmlDocument.PropertyNames.RedirectingPage] = "False";
            this.SearchProperties[HtmlDocument.PropertyNames.FrameDocument] = "False";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Details";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "/ServiceTickets/Details/17";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "http://intranet.fabrikam.com/ServiceTickets/Details/17";
            this.WindowTitles.Add("Details");
            #endregion
        }
        
        #region Properties
        public UIContentCustom1 UIContentCustom
        {
            get
            {
                if ((this.mUIContentCustom == null))
                {
                    this.mUIContentCustom = new UIContentCustom1(this);
                }
                return this.mUIContentCustom;
            }
        }
        #endregion
        
        #region Fields
        private UIContentCustom1 mUIContentCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIContentCustom1 : HtmlCustom
    {
        
        public UIContentCustom1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties["Id"] = "content";
            this.SearchProperties[UITestControl.PropertyNames.Name] = null;
            this.SearchProperties["TagName"] = "SECTION";
            this.FilterProperties["Class"] = null;
            this.FilterProperties["ControlDefinition"] = "id=\"content\"";
            this.FilterProperties["TagInstance"] = "1";
            this.WindowTitles.Add("Details");
            #endregion
        }
        
        #region Properties
        public HtmlCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.SearchProperties["Id"] = null;
                    this.mUIItemCustom.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUIItemCustom.SearchProperties["TagName"] = "P";
                    this.mUIItemCustom.FilterProperties["Class"] = "display-field";
                    this.mUIItemCustom.FilterProperties["ControlDefinition"] = "class=\"display-field\"";
                    this.mUIItemCustom.FilterProperties["TagInstance"] = "1";
                    this.mUIItemCustom.WindowTitles.Add("Details");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        
        public HtmlCustom UIItemCustom1
        {
            get
            {
                if ((this.mUIItemCustom1 == null))
                {
                    this.mUIItemCustom1 = new HtmlCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom1.SearchProperties["Id"] = null;
                    this.mUIItemCustom1.SearchProperties[UITestControl.PropertyNames.Name] = null;
                    this.mUIItemCustom1.SearchProperties["TagName"] = "P";
                    this.mUIItemCustom1.FilterProperties["Class"] = "display-field";
                    this.mUIItemCustom1.FilterProperties["ControlDefinition"] = "class=\"display-field\"";
                    this.mUIItemCustom1.FilterProperties["TagInstance"] = "3";
                    this.mUIItemCustom1.WindowTitles.Add("Details");
                    #endregion
                }
                return this.mUIItemCustom1;
            }
        }
        #endregion
        
        #region Fields
        private HtmlCustom mUIItemCustom;
        
        private HtmlCustom mUIItemCustom1;
        #endregion
    }
}
